version: "3.3"

services:

  matcha_app:
    container_name: 'matcha_app'
    restart: always
    depends_on:
      - matcha_db
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app
    env_file:
      - ./backend/.env.app.dev
    networks:
      - backend-net

  matcha_db:
    container_name: 'matcha_db'
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.db.dev
    networks:
      - backend-net
      

volumes:
  postgres-data:

networks:
  backend-net:
