version: "3.3"

services:
  matcha_app:
    container_name: "matcha_app"
    restart: always
    depends_on:
      - matcha_db
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app
      - ./backend/uploads:/home/node/app/uploads
    env_file:
      - ./backend/.env.app.dev
    networks:
      - backend-net

  matcha_db:
    container_name: "matcha_db"
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.db.dev
    networks:
      - backend-net

  matcha_adminer:
    container_name: "matcha_adminer"
    image: adminer
    ports:
      - 9000:8080
    links:
      - "matcha_db:db"
    depends_on:
      - matcha_db
    networks:
      - backend-net
    restart: always

volumes:
  postgres-data:

networks:
  backend-net:
