version: "3.3"

services:
  matcha_app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/home/node/app
  matcha_db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data: